name: Make web and commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout the same branch for teddycloud_web
        run: |
          # Get the current branch of the parent project
          PARENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # Checkout the same branch in the submodule
          cd teddycloud_web
          git checkout $PARENT_BRANCH || git checkout -b $PARENT_BRANCH
          cd ..

      - name: Update teddycloud_web submodule
        run: git submodule update --remote teddycloud_web

      - name: Git status
        run: |
          git status
          git submodule status
          cd teddycloud_web
          git status
          cd ..

      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
      - name: Install NPM version
        run: npm install -g npm@10.8.2

      - name: Disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Make Web
        run: make web

      - name: Configure Git
        run: |
          git config --global user.email "scilor@users.noreply.github.com"
          git config --global user.name "SciLor"

      - name: Commit and push if changed
        run: |
          if [[ -n $(git status --porcelain) ]]; then
          git add .
          git commit -m "Update frontend (make web)"
          git pull --rebase
          git push
          else
          echo "No changes to commit and push."
          fi
