name: Make web and commit

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update teddycloud_web submodule
      run: git submodule update --remote teddycloud_web

    - uses: actions/setup-node@v4
      with:
        node-version: "12.22.9"

    - name: Make Web
      run: make web

    - name: Configure Git
      run: |
        git config --global user.email "scilor@users.noreply.github.com"
        git config --global user.name "SciLor"
        
    - name: Git status
      run: |
        git status
    - name: Commit and push if changed
      run: |
        if [[ -n $(git status --porcelain) ]]; then
        git add .
        git commit -m "Update webinterface"
        git pull --rebase
        else
        echo "No changes to commit and push."
        fi