name: Restrict PRs to Master

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

permissions:
  pull-requests: write
  issues: write

jobs:
  check_pr_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR creator's permissions
        id: check_permissions
        run: |
          curl -s -X GET \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/collaborators/${GITHUB_ACTOR}/permission \
          -H 'Authorization: Bearer $GITHUB_TOKEN' \
          -H 'Accept: application/vnd.github.v3+json' \
          | jq '.permission' > permission.txt 2>/dev/null || echo "read" > permission.txt

          if [ "$(cat permission.txt)" != "admin" ] && [ "$(cat permission.txt)" != "write" ]; then
            echo "::set-output name=result::false"
          else
            echo "::set-output name=result::true"
          fi

      - name: Close PR
        if: steps.check_permissions.outputs.result == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr close --comment "Please use the develop branch as base! This PR will be closed, as the master is only used for releases." ${{ github.event.pull_request.number }}

      - name: Lock conversation
        if: steps.check_permissions.outputs.result == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/lock \
            -f lock_reason='resolved'
