name: Docker Image Publish Matrix (All New)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tcw_commit_hash:
        type: string

jobs:
  test_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ inputs.tcw_commit_hash }}

      - name: Verify commit hash
        if: ${{ inputs.tcw_commit_hash != '' }}
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          if [ "$COMMIT_HASH" != "${{ inputs.tcw_commit_hash }}" ]; then
            echo "Error: Checked out commit hash ($COMMIT_HASH) does not match the expected hash (${{ inputs.tcw_commit_hash }})."
            exit 1
          else
            echo "Commit hash verified: $COMMIT_HASH"
          fi

  ubuntu:
    needs: test_commit_hash
    uses: ./.github/workflows/publish_docker_matrix_all.yml
    with:
      system: "ubuntu"
      dockerfile: "DockerfileUbuntu"
      platforms: '["linux/amd64", "linux/arm/v7", "linux/arm64/v8", "linux/ppc64le", "linux/s390x"]'
      primary_image: true
      error_platforms: '["linux/s390x", "linux/ppc64le", "linux/arm/v7"]'
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
  debian:
    needs: test_commit_hash
    uses: ./.github/workflows/publish_docker_matrix_all.yml
    with:
      system: "debian"
      dockerfile: "DockerfileDebian"
      platforms: '["linux/amd64", "linux/arm/v7", "linux/arm64/v8", "linux/i386", "linux/ppc64le", "linux/s390x"]'
      primary_image: false
      error_platforms: '["linux/s390x", "linux/ppc64le", "linux/arm/v7"]'
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
  alpine:
    needs: test_commit_hash
    uses: ./.github/workflows/publish_docker_matrix_all.yml
    with:
      system: "alpine"
      dockerfile: "DockerfileAlpine"
      platforms: '["linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64/v8", "linux/ppc64le", "linux/s390x", "linux/386"]'
      primary_image: false
      error_platforms: "[]"
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
