name: Docker Image Publish Matrix (All)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tcw_commit_hash:
        description: "Commit hash from the teddycloud_web build job"
        type: string
        required: false

  push:
    branches:
      - master
      - develop
    tags:
      - tc_nightly*
      - tc_v*.*.*
  pull_request:
    branches: ["master", "develop"]

jobs:
  debian:
    uses: ./.github/workflows/publish_docker_matrix_debian.yml
    with:
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
  ubuntu:
    uses: ./.github/workflows/publish_docker_matrix_ubuntu.yml
    with:
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
  alpine:
    uses: ./.github/workflows/publish_docker_matrix_alpine.yml
    with:
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
