name: Docker Image Publish Matrix (All)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tcw_commit_hash:
        type: string

  push:
    branches:
      - master
      - develop
    tags:
      - tc_nightly*
      - tc_v*.*.*
  pull_request:
    branches:
      - master
      - develop

jobs:
  test_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ inputs.tcw_commit_hash }}

      - name: Verify commit hash
        if: inputs.tcw_commit_hash != ''
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          if [ "$COMMIT_HASH" != "${{ inputs.tcw_commit_hash }}" ]; then
            echo "Error: Checked out commit hash ($COMMIT_HASH) does not match the expected hash (${{ inputs.tcw_commit_hash }})."
            exit 1
          else
            echo "Commit hash verified: $COMMIT_HASH"
          fi

  debian:
    needs: test_commit_hash
    uses: ./.github/workflows/publish_docker_matrix_debian.yml
    with:
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
  ubuntu:
    needs: test_commit_hash
    uses: ./.github/workflows/publish_docker_matrix_ubuntu.yml
    with:
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
  alpine:
    needs: test_commit_hash
    uses: ./.github/workflows/publish_docker_matrix_alpine.yml
    with:
      tcw_commit_hash: ${{ inputs.tcw_commit_hash }}
