name: Docker Image Publish Matrix (All)

on:
  workflow_dispatch:
  workflow_call:

  push:
    branches:
    - master
    - develop
    tags:
    - tc_nightly*
    - tc_v*.*.*
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  debian:
    uses: ./.github/workflows/publish_docker_matrix_debian.yml
  ubuntu:
    uses: ./.github/workflows/publish_docker_matrix_ubuntu.yml
  alpine:
    uses: ./.github/workflows/publish_docker_matrix_alpine.yml