name: Docker Image Publish Matrix (All)

on:
  workflow_dispatch:
  workflow_call:

  push:
    branches:
    - master
    - develop
    tags:
    - tc_nightly*
    - tc_v*.*.*
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  generate-workflows-list:
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.discover_workflows.outputs.matrix_json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Discover Workflows
        id: discover_workflows
        run: |
          # Find all YAML files in the .github/workflows directory that start with "publish_docker_matrix_"
          workflows=$(find .github/workflows -name 'publish_docker_matrix_*.yml' -exec basename {} \;)
          echo "Found workflows: $workflows"
          # Convert to JSON array
          matrix_json=$(echo "$workflows" | tr ' ' '\n' | sed 's/^/"/;s/$/"/' | paste -sd, - | sed 's/^/[ /;s/$/ ]/')
          echo "matrix_json=$matrix_json" >> $GITHUB_ENV

      - name: Trigger Workflow Debian
        uses: ./.github/workflows/publish_docker_matrix_debian.yml
        with:
          branch: ${{ github.ref_name }}  # Passing the current branch name
          secrets: inherit  # Inherit secrets from the calling workflow
      - name: Trigger Workflow Ubuntu
        uses: ./.github/workflows/publish_docker_matrix_ubuntu.yml
        with:
          branch: ${{ github.ref_name }}  # Passing the current branch name
          secrets: inherit  # Inherit secrets from the calling workflow
      - name: Trigger Workflow Alpine
        uses: ./.github/workflows/publish_docker_matrix_alpine.yml
        with:
          branch: ${{ github.ref_name }}  # Passing the current branch name
          secrets: inherit  # Inherit secrets from the calling workflow

#  trigger-workflows:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        workflow: ${{ fromJson(needs.generate-workflows-list.outputs.matrix_json) }}

#    steps:
#      - name: Trigger Workflow ${{ matrix.workflow }}
#        uses: ./.github/workflows/${{ matrix.workflow }}
#        with:
#          branch: ${{ github.ref_name }}  # Passing the current branch name
#          secrets: inherit  # Inherit secrets from the calling workflow