name: Restrict PRs to Master

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

permissions:
  pull-requests: write
  issues: write

jobs:
  check_pr_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR creator's permissions
        id: check-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const creator = context.payload.pull_request.user.login;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            
            console.log(`PR created by: ${creator}`);
            console.log(`Repository: ${owner}/${repo}`);
            
            try {
              console.log('Checking creator\'s permission level...');
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: owner,
                repo: repo,
                username: creator
              });
              
              console.log(`Creator's permission level: ${permission.permission}`);
              
              const canPush = ['admin', 'write'].includes(permission.permission);
              console.log(`Can creator push? ${canPush}`);
              
              if (!canPush) {
                console.log('Creator does not have push access.');
                return false;
              } else {
                console.log('Creator has push access.');
                return true;
              }
            } catch (error) {
              console.error('Error occurred:', error);
              if (error.status === 404) {
                console.log('Creator is not a collaborator.');
                console.log('false');
                return false;
              }
            }
            
      - name: Get result
        run: echo "${{steps.check-pr.outputs.result}}"
        
      - name: Close PR and add comment
        if: steps.check-pr.outputs.result == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh auth login --with-token $GH_TOKEN
          gh pr close --comment "Please use the develop branch as base! This PR will be closed, as the master is only used for releases." ${{ github.event.pull_request.number }}
