name: Restrict PRs to Master

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  check_pr_creator:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR creator's permissions
        id: check_permissions
        run: |
          curl -s -X GET \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/collaborators/${GITHUB_ACTOR}/permission \
          -H 'Authorization: Bearer $GITHUB_TOKEN' \
          -H 'Accept: application/vnd.github.v3+json' \
          | jq '.permission' > permission.txt 2>/dev/null || echo "read" > permission.txt

          if [ "$(cat permission.txt)" != "admin" ] && [ "$(cat permission.txt)" != "write" ]; then
            echo "::set-output name=result::false"
          else
            echo "::set-output name=result::true"
          fi

      - name: Close PR
        if: steps.check_permissions.outputs.result == 'false'
        run: gh pr close "$NUMBER" --repo "$GH_REPO"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
            
      - name: Close Comment PR
        if: steps.check_permissions.outputs.result == 'false'
        run: gh pr close "$NUMBER" --comment "$COMMENT" --repo "$GH_REPO"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          COMMENT: >
            Please use the develop branch as base! 
            This PR will be closed, as the master is only used for releases.
