name: Restrict PRs to Master

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

permissions:
  pull-requests: write
  contents: read

jobs:
  check_pr_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR creator's permissions
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const creator = context.payload.pull_request.user.login;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            
            console.log(`PR created by: ${creator}`);
            console.log(`Repository: ${owner}/${repo}`);
            
            try {
              console.log('Checking creator\'s permission level...');
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: owner,
                repo: repo,
                username: creator
              });
              
              console.log(`Creator's permission level: ${permission.permission}`);
              
              const canPush = ['admin', 'write'].includes(permission.permission);
              console.log(`Can creator push? ${canPush}`);
              
              if (!canPush) {
                console.log('Creator does not have push access. Closing PR...');
                await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: context.issue.number,
                  body: 'Please use the develop branch as base! This PR will be closed, as the master is only used for releases.'
                });
                
                await github.rest.pulls.update({
                  owner: owner,
                  repo: repo,
                  pull_number: context.issue.number,
                  state: 'closed'
                });
                console.log('PR closed and comment added.');
              } else {
                console.log('Creator has push access. No action taken.');
              }
            } catch (error) {
              console.error('Error occurred:');
              console.error(error);
              
              if (error.status === 404) {
                console.log('Creator is not a collaborator. Closing PR...');
                await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: context.issue.number,
                  body: 'Please use the develop branch as base! This PR will be closed, as the master is only used for releases.'
                });
                
                await github.rest.pulls.update({
                  owner: owner,
                  repo: repo,
                  pull_number: context.issue.number,
                  state: 'closed'
                });
                console.log('PR closed and comment added.');
              }
            }
